### ISSUE TITLE
Support longer meta descriptions

### ISSUE THREAD

**Issue by maximbrykin** [semperfiwebdesign/all-in-one-seo-pack#1395]
Good day! Update your WP-plugin please! Google already support long descriptions - but All in One SEO Pack is cutting them now 😮

**Comment by michaeltorbert** [comment]
@maximbrykin  First, there's no need to to use exclamation points. Just say what you want to say. I'm editing your submission to remove the exclamation points and to make your title appropriate.

Second, please provide specific information about the exact lengths you're suggesting, along with links to supporting documentation.

**Comment by tonyzeoli** [comment]
I'm not sure, but he could be talking about this:

https://en.ryte.com/magazine/google-is-testing-longer-snippets-more-space-for-titles-and-descriptions

Or, this:

https://seopressor.com/blog/google-increases-title-meta-description-length/

Or, this:

https://www.searchenginejournal.com/google-titles-and-descriptions-2016/163812/

All in May of 2016.

I don't see documentation in my search on this change from Google
themselves, but I do see that Product descriptions can be longer for the
Google Merchant Center -
https://support.google.com/merchants/answer/6098336?hl=en

**Comment by michaeltorbert** [comment]
@tonyzeoli I'm familiar with the idea that titles are measured by pixels, and are longer than they previously were, but before we change anything, we need to know conclusively what they should be.
Everywhere says something different.

**Comment by tonyzeoli** [comment]
Agreed - there needs to be consensus and finality to these types of
decisions. Just because a bunch of people uncover something doesn't mean
it's absolute. Better to be safe, than sorry later.

**Comment by maximbrykin** [comment]
https://searchengineland.com/google-officially-increases-length-snippets-search-results-287596

**Comment by michaeltorbert** [comment]
This has been requested numerous times lately.

**Comment by tonyzeoli** [comment]
Per maximbrykin's post, he may not have read this or ignored it altogether: "Some webmasters and SEOs may consider updating their meta descriptions, but I don’t believe Google would recommend doing so. The snippets are more often dynamically generated based on the user query and content found in both the meta description and the content visible on the page. If Google is going to go with a longer snippet, it likely will pull that content from the page."

**Comment by wpsmort** [comment]
The only official statement that I can find from Google is on Twitter here - https://twitter.com/dannysullivan/status/936708405363843072?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fwww.seroundtable.com%2Fgoogle-extends-snippets-320-characters-24862.html

There's more Tweets in this article here - https://www.seroundtable.com/google-extends-snippets-320-characters-24862.html

My recommendation is that we increase the character counter to 320 characters.

**Comment by michaeltorbert** [comment]
One way we could handle this is to not cut off a manually entered description at all. If the user enters 5000 characters, that's up to them.
We can decide whether or not to increase the recommended amount via character count on the back-end though.

**Comment by wpsmort** [comment]
I agree with the recommendation by @michaeltorbert

**Comment by michaeltorbert** [comment]
- [ ] Manually entered meta descriptions shouldn't be cut off at all
- [ ] auto-generated meta descriptions should be increased to 320 characters
- [ ] the recommended counter on the back-end should go up to 320 characters

**Comment by wpsmort** [comment]
@michaeltorbert I have tested PR #1454 and verified that:

- Manually entered meta descriptions aren't cut off at all.
- Auto-generated meta descriptions have been increased to 320 characters.
- The character counter has been changed to 230 characters for yellow and 320 characters for red.
- The recommendation text has been changed to "Most search engines use a maximum of 230-320 characters".  This last one is correct in all locations except the Home Description field under Home Page Settings.
- I did not see a filter so was unable to test that.  

I have notified @EkoJr about the last two items.

I also verified that the functionality associated with Autogenerated Descriptions for the following still works as expected:

Use Content For Autogenerated Descriptions
Run Shortcodes In Autogenerated Descriptions
Remove Descriptions For Paginated Pages
Never Shorten Long Descriptions

**Comment by michaeltorbert** [comment]
I've added an issue for filters. We can take care of that later. #1459

@wpsmort Is there anything else you think should be done for this issue other than the wording for the home description option?

**Comment by EkoJr** [comment]
(Comment from PR)

1. I updated all my branches, and added 2.4.3. Did you want me to rebase onto 2.4.3 as well?
2. The filter was a pre-existing filter `aiosp_dont_truncate_descriptions`. [Located here](https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1454/files#diff-4e533641bc4be27bca19bde1a2b60fe9R2564)
```
$description = apply_filters(
    'aioseop_description',
    $description,
    empty( $aioseop_options['aiosp_dont_truncate_descriptions'] )
);
```
3. I saw another 'if' check, which checks if it is already set, and may be the cause of it...but was unsure what implications it had. [all-in-one-seo-pack/admin/aioseop_module_class.php on Line 2257](https://github.com/EkoJr/all-in-one-seo-pack/blob/f17df674552dc4204130dee721fbdcfa1c2c3b7b/admin/aioseop_module_class.php#L2257)

**Comment by michaeltorbert** [comment]
@EkoJr For 3, that seems to be set on https://github.com/EkoJr/all-in-one-seo-pack/blob/f17df674552dc4204130dee721fbdcfa1c2c3b7b/admin/aioseop_module_class.php#L2791

**Comment by wpsmort** [comment]
I've added a separate issue for the Home Description text here - #1464
