### ISSUE TITLE
Virtual Robots.txt module

### ISSUE THREAD

**Issue by wpsmort** [semperfiwebdesign/all-in-one-seo-pack#1647]
This is the master issue for the new virtual Robots.txt module.  The following tasks need to be completed:

- [x] Robots.txt should filter built-in WordPress virtual robots.txt (old issue #214)
- [x] Remove all code related to handling a physical robots.txt file
- [x] Remove Robots.txt tab from File Manager module (old issue #213)
- [x] Remove the Optimize your Robots.txt File functionality from current module
- [x] Remove Save Robots.txt File button and Delete Robots.txt File button from current module
- [x] Store all robots.txt rules in database
- [x] Sanitize entries before writing to the database
- [x] Sanitize paths to add trailing slash when none is present
- [x] Check for presence of a physical robots.txt file and display a warning with prompts to Import and delete existing file, delete existing file, do nothing (old issue #596)
- [x] Import existing physical robots.txt file when user visits the Robots.txt module
- [x] Sanitize the import of existing physical robots.txt file during import 
- [x] Support WordPress multisite with sub domain installs (old issue #1143)
- [x] Support WordPress multisite with domain mapping (old issue #1124)
- [x] Network Admins should be able to set default rules (old issue #1600)
- [x] Check for duplicates or conflicts for rules added by Site Admin to rules added by Network Admin
- [x] Allow wildcards in rules and check for duplicates or conflicts

**Comment by wpsmort** [comment]
Google has a developer doc for robots.txt that is a must read regarding order of precedence - https://developers.google.com/search/reference/robots_txt

In testing I found that when there is a Disallow directive and an Allow directive in the same group, the Allow directive always overrides the Disallow regardless of its position within the group (for example, the Allow can be before or after the Disallow, it will always match). This is not mentioned in the developer doc.

**Example of trailing slash precedence in robots.txt:**

User-agent: Googlebot-Image
Disallow: /wp-content/image-test  -  This Network Admin rule is intended to take precedence but it's missing the trailing slash

User-agent: Googlebot-Image
Allow: /wp-content/image-test/  -  This Site Admin rule takes precedence for the directory because it has the trailing slash

**Desired outcome above is that we enforce strict paths so that the Network Admin rule has the correct trailing slash and takes precedence over the Site Admin rule.**

------
**Example of rule matching:***

User-agent: Googlebot-Image
Disallow: /wp-content/image-test/  -  This is Network Admin rule is intended to take precedence 

User-agent: Googlebot-Image
Allow: /wp-content/image-test/  -  This Site Admin rule duplicates and overrides the Network Admin rule

**Desired outcome above is that a Site Admin cannot duplicate an existing rule thereby overriding  a Network Admin rule.**

------
**Example of wildcard precedence in robots.txt:**

User-agent: Googlebot
Allow: /wp-content/image-test/  -  This Network Admin rule is intended to take precedence and block ALL Googlebots from that directory but it's overridden by the wildcard rule below

User-agent: Googlebot-Image
Disallow: /wp-*    -  This Site Admin wildcard rule will take precedence because it's specific for Googlebot-Image and has a wildcard

**Desired outcome above is that a Site Admin cannot override by specifying a different User-agent and using wildcards.**

**Comment by wpsmort** [comment]
Reported here - https://wordpress.org/support/topic/robots-txt-not-working-on-multisite/#post-9469713

Currently we create a static file for the robot.txt which means that there's one file for a multisite network. If domain mapping is active on the multisite then this causes problems because the sitemap URL will be wrong for all but the primary site.

**Comment by contactashish13** [comment]
if we are not showing the editable text area, no one can delete rules once added. Suggestions?

**Comment by michaeltorbert** [comment]
Yes, that's a UI problem that will need to be solved.

**Comment by wpsmort** [comment]
Currently the grey box is a text area field.  We could change it to a table with one column and a row for each rule.  If we did this as a table we could have the ability for users to both delete a row and also edit a row.  We'd have a delete icon and an edit icon placed to the left of each row.

We would have to group rows based on the User Agents and we'd have to automatically remove the User Agent row if there are no rules present.  For example, I delete the one rule below which means that the User Agent also gets removed:

User Agent: Googlebot
Disallow: /wp-admin/

Is this a practical solution and is there a library we could use that would provide what we need?

**Comment by contactashish13** [comment]
I think that's the easiest way to do this.

This also means we would need to track the rules added by each site admin so that they can delete their own rules. 

The network admins can edit/delete the rules created by them. But the grey box will contain the fully formed robots.txt.

**Comment by contactashish13** [comment]
@wpsmort @michaeltorbert could you comment on the above?

**Comment by contactashish13** [comment]
@wpsmort what if Admin A wants to delete/edit his own rules? Do we want them to have this ability or only to add and do nothing else? If they should be able to edit/delete their own rules, we need to track who added what rule so that we don't show them someone else's rules to edit/delete

**Comment by wpsmort** [comment]
@contactashish13 We want to allow any administrator to make changes to site admin rules.  We don't need to track which administrator adds, edits or deletes rules.  

If you and I are both admins on the same site then we can both make whatever changes we want.  If you want to delete something that I added then that's fine.  We only need to track and protect Network Admin rules.

**Comment by contactashish13** [comment]
How about if we are from different sites? Can I delete your rules and vice versa?

**Comment by wpsmort** [comment]
You can only add, edit or delete rules on a site if you have administrator role on that site.

**Comment by contactashish13** [comment]
@wpsmort Let me make the scenario clear:

1. You are the admin for site 1
2. I am the admin for site 2
3. Michael is the network admin

If I add rules
* can you delete then?
* can I edit/delete them without tracking which rules I added?

If you add rules,
* can I delete then?
* can you edit/delete them without tracking which rules you added?

Michael can delete only his rules because those are network wide rules.

**Comment by wpsmort** [comment]
If I’m not an Administrator on your site then I don’t have permission to log into your site and therefore cannot change any setting on your site. This doesn’t change if it’s a Multisite. When a user is created for a site in a Multisite network then they only have that role for that site. They can’t log into any other site in the network.

Does that clear things up?

**Comment by contactashish13** [comment]
@wpsmort I don't think the current UI makes sense if we are going to introduce another table underneath it for individual rules. 

Something like https://datatables.net/examples/api/form.html might be more in line with what we want to do - addition/editing/deleting. Each user can then have the ability to add/edit/delete rows and then submit the whole table. Let me know what you think.

**Comment by wpsmort** [comment]
@contactashish13 I agree that a table UI would be better suited to what we want to do so that individual rules can be edited or deleted.

**Comment by michaeltorbert** [comment]
If we do change the UI, two things we need to keep in mind:

1) The UI should be clean and intuitive. WP of course has a built in UI that could be used (for posts, etc), or something like the Cart66 data tables UI.
2) We need to keep in mind security of the inputs. We don't want to open up any new vulnerabilities.

**Comment by contactashish13** [comment]
@wpsmort in a multisite there are 3 types of admin users. 

1. Network admin - can manage plugins and thus can add robots rules
2. Admin of child sites - can manage plugins and thus can add robots rules
3. Admin of the **main** site - **cannot** manage plugins and thus **cannot** add robots rules

Therefore the visibility rules will apply to only the first 2 types of users.

**Comment by wpsmort** [comment]
@contactashish13 I was only aware of the first two.  Where did you see about the third?

**Comment by michaeltorbert** [comment]
I would assume we'd treat 2 and 3 as the same thing for our purposes.

**Comment by contactashish13** [comment]
no we can't. that user does not have manage_options capability

**Comment by contactashish13** [comment]
@wpsmort PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1669

**Comment by wpsmort** [comment]
@contactashish13 Here are the results of my testing today.  I only tested with a single site install (not Multisite):

- The default WordPress robots.txt rules need to be saved in the database when the module is activated.  If this isn't done then we're missing those rules and aren't doing any duplicate or conflict matching on them.
- On import of a static robots.txt file, we need to remove duplicate or conflicting rules.  For example, if my static robots.txt file has the rule Allow: /wp-admin/ then that would conflict with the default WordPress robots.txt rules that should be in the database.
- We need to correct filesystem paths when importing rules from a static robots.txt file.  For example, slashes aren’t added if they are missing in the rule in a static file. 
- Conflicts are not being correctly identified when wildcards are used.  

These errors occurred when adding a conflicting rule:
* PHP Warning:  uasort() expects parameter 1 to be array, string given in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 383
* PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 396
* The entry in the database has &quot; added when a conflicting or duplicate rule is added

These errors occurred trying to add a new rule after a conflict has happened:
* PHP Warning:  Invalid argument supplied for foreach() in /wp-includes/class-wp-list-util.php on line 148
* PHP Warning:  in_array() expects parameter 2 to be array, string given in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 343
* PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 349
* PHP Warning:  in_array() expects parameter 2 to be array, string given in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 360
* PHP Warning:  Invalid argument supplied for foreach() in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 366
* PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php:304

**Comment by contactashish13** [comment]
@wpsmort we'll need to test on a common instance as I am not getting those errors. Can you please share the credentials?

**Comment by wpsmort** [comment]
@contactashish13 I will send you access info for my test site via Slack. 

I tested your latest commit and when I activate the Robots module in Feature Manager I get these warnings and notices:

- PHP Notice:  Undefined index: modules in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 276
- PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 276

When adding a duplicate rule I get this notice:

- PHP Notice:  Undefined variable: rule in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 418

In addition, I have these comments:
- Checking for duplicate or conflicting rules is now working when a static file is imported.
- Slashes are being added to the end of filenames, they should only be added to the end of directories. This happens with imports as well as adding rules.
- It should be possible to delete the rules added from the default WordPress robots.txt.  Currently they don't appear in the table so can't be deleted.
- It's still possible to use a wildcard to create a duplicate or conflicting rule.  Here are examples:

Existing rules in the robots.txt:
Disallow: /test.jpg 
Disallow: /wp-admin/

New conflicting rules that should not be allowed:
Allow: /*.jpg
Allow: /wp-*/

**Comment by contactashish13** [comment]
@wpsmort could you list down all the possible conflicting rules please so that it can be addressed in one go?

Also, any conditions such as 

> It should be possible to delete the rules added from the default WordPress robots.txt.

**Comment by wpsmort** [comment]
@contactashish13 I've created a Google spreadsheet with rules to test with here - https://docs.google.com/spreadsheets/d/1bRZPhoo4MurkfFHlQo-CucNp4DhASajw6Zmtka-vaRM/edit?usp=sharing

If I think of any more rules or test cases I will add them to the doc.

**Comment by contactashish13** [comment]
@wpsmort I've added comments to that spreadsheet. The most vexing problem will be to collect all possible wild card scenarios, weeding out the false positives and then arrive at an algorithm that will fit the valid scenarios.

**Comment by wpsmort** [comment]
@contactashish13 I added one comment to the spreadsheet.  I also tested your latest commit found one new problem:

- When importing a static robots.txt file I get this Fatal Error: 
PHP Fatal error:  Cannot use object of type WP_Error as array in /wp-content/plugins/all-in-one-seo-pack--1647/modules/aioseop_robots.php on line 221

**Comment by contactashish13** [comment]
@wpsmort I've responded to your comment. Have rectified the error as well.

**Comment by wpsmort** [comment]
@contactashish13 I tested this morning and only found one new problem:

- Identical rules are deleted when a static file is imported

To test this follow these steps:

Add a rule for Disallow: /wp-includes/ and confirm it's in the database
Import a static robots.txt with the same rule and see if the rule is deleted from the database
Correct behavior should be to ignore duplicates upon import and leave the existing rule in place

**Comment by wpsmort** [comment]
@contactashish13 With regards to the default WordPress rules, these should not be stored in the database array.  This should be the case for any rules added by a third party, whether it's WordPress or another plugin.

**Comment by wpsmort** [comment]
@contactashish13 I tested with WordPress Multisite sub-directory install and found the following problems:

1).  The rules on a site in the network are displayed with different paths depending on how they were added. For example:

The default rules from WordPress have the site name in the path which I believe is correct:
Disallow: /site-name/wp-admin/ 

Whereas rules added by a Network Admin at the network level or Site Admin at the site level don't have the site name in the path:
Disallow: /wp-includes/

2).  When browsing to the robots.txt URL on a site in the network I get a 404 error.  The only robots.txt I can browse to is the one for the root site.

I've set up a test environment and sent you the details on Slack.

**Comment by contactashish13** [comment]
@wpsmort I'm not sure what you mean by the below as it contradicts https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1647#issuecomment-383769631

And if we don't save it in the database how will we verify conflicts? 

> With regards to the default WordPress rules, these should not be stored in the database array. This should be the case for any rules added by a third party, whether it's WordPress or another plugin.

**Comment by contactashish13** [comment]
@wpsmort I'm not sure https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1647#issuecomment-384670397 is a valid test case. If you are adding the rule to the database array using the plugin interface and then importing a static file, this will obviously not work as its not designed for an upside-down approach. The intent is to import a static file **before** any rule gets added to the database. Please confirm if my understanding is correct.

**Comment by contactashish13** [comment]
@wpsmort for https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1647#issuecomment-384772117

> 2). When browsing to the robots.txt URL on a site in the network I get a 404 error. The only robots.txt I can browse to is the one for the root site.

are you able to do this when the plugin is not active?

**Comment by wpsmort** [comment]
@contactashish13 I agree that https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1647#issuecomment-384670397 is not a valid test case.  You can ignore that comment.

For Multisite Network testing:
I deactivated AIOSEOP and was not able to browse to the robots.txt created by WordPress so it's a site issue.  I'll troubleshoot and see if I can find out why that's happening as it'll need to be fixed before I can do any more testing on Multisite.

**Comment by wpsmort** [comment]
@contactashish13 The issue with the robots.txt not working on Multisite with sub directories can be ignored.  WordPress doesn't create a robots.txt in a sub directory and Google specifically states that "The robots.txt file must be in the top-level directory of the host" (https://developers.google.com/search/reference/robots_txt).  We should therefore only create the one virtual robots.txt on Multisite with sub domains.

**Comment by michaeltorbert** [comment]
@wpsmort What about subdomains?

Also, I just want to point out that we need to make sure we're testing when using separate domains, if we aren't already. You may want to help set up a server he can use for that if we have some spare domains laying around.

**Comment by wpsmort** [comment]
@michaeltorbert I have a Multisite with sub domains set up for testing and so far testing has been fine on this site.  I've sent @contactashish13 the access information for this site.

I'm going to set up a Multisite with domain mapping next and test with that and share access.  I'm also providing @arnaudbroes with access to everything and bringing him up to speed on testing.

**Comment by contactashish13** [comment]
@wpsmort what is the implication of https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1647#issuecomment-386014285 in the context of testing? Does any behavior change?

**Comment by wpsmort** [comment]
@contactashish13 I'm still testing with the different types of Multisite setup, however, one thing that it means is that there will be one virtual robots.txt for all sites so rules will need to have the full path from root.  For example:

Root site: mydomain.com
Sub site 1:  mydomain.com/site-1/
Sub site 2: mydomain.com/site-2/

Rules for Sub site 1 would need to look like this:

Disallow: /site-1/wp-content/

Does that make sense?  Can you think of any problems here?

**Comment by wpsmort** [comment]
@contactashish13 With regards to Multisite with sub directories we'll need to prefix rules created by site admins on individual sites with the sub directory so the path os correct from root, for example:

Allow: /sub-directory/wp-admin/

Site Admins should not be able to override rules added by Network Admins.  

If you can update the code and let me and @arnaudbroes know so we can test.

**Comment by wpsmort** [comment]
@contactashish13 I would handle it like this:

Network Admins can add rules for any site but they have to input the full path for the site when they add the rule, for example: 

Allow: /site-01/wp-content/

Site Admins can add rules for their site and we'll automatically add the site path for them.

Site Admins should never be able to override Network Admins rules.  That goes for any type of Multisite install.

**Comment by contactashish13** [comment]
@wpsmort Currently I'm displaying only the network rules + the requested blog's rules. Does the above also mean that when robots.txt is displayed it should display the rules for all sites in the network? If so, this is definitely something that was not considered before.

**Comment by wpsmort** [comment]
@contactashish13 We have decided not to support Multisite with sub-directories at this time so you do not need to do anything more for that.

I've completed testing of Multisite with sub-domains and Multisite with domain mapping.  I have found three issues which need to be addressed.  These are detailed below and in the Google spreadsheet.  In the Google spreadsheet you will see access information for the sites where you can reproduce these issues.

1. There's still an issue with wildcard matching that results in rules not being added.  
2. I was able to add conflicting rules as a Site Admin.  
3. The default WordPress robots rules are being stored in the database. 

Can you ping me on Skype or Slack when you are available and we can run through these last three items together.

**Comment by contactashish13** [comment]
@wpsmort I've responded to your comments on the sheet.

**Comment by wpsmort** [comment]
@contactashish13 I've updated the sheet with my comments and uploaded a video of me demonstrating the conflicting rule issue.

**Comment by contactashish13** [comment]
@wpsmort can you please test with the latest commit?

**Comment by wpsmort** [comment]
@contactashish13 The latest commit fixes the problem with the wildcard rules.  I updated the Google sheet with one comment.  Please take a look at the last three remaining items on that sheet.

**Comment by wpsmort** [comment]
@contactashish13 I tested the last commit and it did not resolve the other two issues on the Google sheet where duplicate rules can be added by a site admin on a multisite.

Try adding the following lines to your local hosts file and you should be able to access that multisite:
```
165.227.199.12	wordpressmu-138706-498093.cloudwaysapps.com
165.227.199.12	test-site-01.wordpressmu-138706-498093.cloudwaysapps.com
165.227.199.12	test-site-02.wordpressmu-138706-498093.cloudwaysapps.com
```

**Comment by contactashish13** [comment]
@wpsmort can you please check with the new commit?

**Comment by wpsmort** [comment]
@contactashish13 I tested the latest commit and updated the Google sheet with my findings.

Also, as discussed, I found a bug which was introduced in this commit - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1669/commits/ade649ef2af0018efa8ab047f1353967eabda035

When you import a static file, the Robots screen changes to output HTML code.  See screenshot:

<img width="1708" alt="screen shot 2018-05-23 at 11 20 16 am" src="https://user-images.githubusercontent.com/17548525/40435640-18f55bec-5e7f-11e8-9d8c-63b0545e338a.png">

**Comment by contactashish13** [comment]
@wpsmort that was the first commit for this entire issue and the commit that is the base for all the testing till now. If things were working thus far, something has to have happened on the installation. Can you please check what has changed?

**Comment by wpsmort** [comment]
@contactashish13 I've tested with a brand new install of WordPress and got the same bug.  See video here - https://www.dropbox.com/s/oetp6onkdw4juxw/robots-issue.mov?dl=0

**Comment by contactashish13** [comment]
@wpsmort I see you mentioned and installed WooCommerce. Do you see this problem without WC or does this happen only with WC?

And in your previous testing since the commit on April 23rd, has all your testing been on instances without WooCommerce?

**Comment by wpsmort** [comment]
@contactashish13 I can only reproduce it locally when I have WooCommerce active, however, on the customer's development site they do not have WooCommerce installed, they have a number of custom plugins installed which I cannot clone or duplicate at this time.

**Comment by wpsmort** [comment]
@contactashish13 I tested your latest commit and it fixes all of the items in yellow on the Google sheet.  As far as duplicating and conflicting rules goes, we're good there.

The only bug left now is this weird bug were the Robots.txt module appears as HTML code when you import a static robots.txt file.  The latest commit didn't have any effect on that.

**Comment by wpsmort** [comment]
@contactashish13 I found one more bug where rules added by a Site Admin on their site in the Multisite don't appear in the box or in the robots.txt file being output.  I traced this back to this commit - https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1669/commits/4641cbe2270c8fc64c4a06d56932bb90e6d51eaf.  Specifically, it was the code below that was removed in that commit that broke this.  Adding this code back fixes the problem.

```
			if ( $this->get_network_id() != get_current_blog_id() ) {
				$rules .= "\r\n" . $this->get_rules_for_blog();
			}
```

**Comment by contactashish13** [comment]
@wpsmort I'm not sure I understand what you mean by

>  or in the robots.txt file being output.

The site admin cannot load the robots.txt for his site. The robots.txt can only be loaded for the network. Therefore the network ID and the current blog ID will always have the same value and those rules will never come into play. Also, the rules will not be ordered according to user-agent.

Can you please confirm the exact scenario?

**Comment by contactashish13** [comment]
@wpsmort I'm unable to reproduce this on my multisite instance. Can you please provide the credentials of your test site?

**Comment by wpsmort** [comment]
@contactashish13 I've sent this to your on Slack.  It's the same login and same test site I've sent you before.

**Comment by contactashish13** [comment]
@wpsmort have fixed that.

**Comment by wpsmort** [comment]
@contactashish13 Thanks Ashish, I tested that and confirmed it fixes that bug.  I have handed this over to our customer to conclude their acceptance testing.

**Comment by wpsmort** [comment]
@contactashish13 The customer reported one bug which appear to be caused by the JavaScript error below:

```
aioseop_module.js?ver=2.6-1647:875 

Uncaught TypeError: $ is not a function
    at initAll (aioseop_module.js?ver=2.6-1647:875)
    at HTMLDocument.<anonymous> (aioseop_module.js?ver=2.6-1647:869)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.6:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.6:2)
    at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.6:2)
    at HTMLDocument.K (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=4.9.6:2)
```

I am able to reproduce this on a brand new site by activating the Robots.txt module and editing a post.  I get the JS error in my browser console.

**Comment by michaeltorbert** [comment]
@contactashish13  What was the purpose of removing jQuery here? Removing it is what is causing the javascript conflict error. https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1669/commits/d41241268b3870ef1790b9cfe07a68bf6e415c35

**Comment by contactashish13** [comment]
@michaeltorbert I changed this to an IIFE instead of exposing all JS functions in the global scope to prevent possible conflicts with other plugins. Thus jQuery is being passed to the entire JS file and the argument is no longer needed by the functions as they will all recognize `$`. Have done this now. Also, there were too many `jQuery(document).ready` instances and I've merged all into one. This will cause less confusion.

**Comment by michaeltorbert** [comment]
@contactashish13 Will this mean https://github.com/semperfiwebdesign/all-in-one-seo-pack/issues/1726 is no longer an issue? I'd changed the names of the two functions in the latest version (which will probably cause a merge conflict btw with your latest commit).

**Comment by contactashish13** [comment]
Yes it should resolve the error. But you can reject the commit in case of merge conflicts as your change would solve the issue anyway.

**Comment by wpsmort** [comment]
@contactashish13 The customer has completed acceptance testing and approved this.  We have one final item that needs to be completed as follows:

Remove General Settings, Performance and all other modules from the menu and Feature Manager when in the Network Admin screen.  

The only menu items that should be visible at the Network Admin level are Robots.txt and Feature Manager.  

The only module that should be visible in the Feature Manager at the Network Admin level is the Robots.txt module.  

See screenshot
![screen shot 2018-06-12 at 12 55 42 pm](https://user-images.githubusercontent.com/17548525/41305159-0997da3c-6e40-11e8-89ff-61b35db08e6a.png)
:

**Comment by contactashish13** [comment]
@wpsmort are these changes specific to the customer or is this behavior for anyone who deploys the plugin?

**Comment by wpsmort** [comment]
@contactashish13 This is for all and for both free and Pro versions.

**Comment by contactashish13** [comment]
@wpsmort reopening this to add test cases. Can you please provide a matrix of rules that a user can provide and the expected results (similar to what you had listed in the spreadsheet) so that I can create test cases around each of them? It would also be great if you can specify multisite/single site next to each rule.

PR: https://github.com/semperfiwebdesign/all-in-one-seo-pack/pull/1803

**Comment by wpsmort** [comment]
@contactashish13 I've updated the Google spreadsheet with some rules for unit testing.  Let me know if you think we need more test rules.  The ones here should cover all cases.

https://docs.google.com/spreadsheets/d/1bRZPhoo4MurkfFHlQo-CucNp4DhASajw6Zmtka-vaRM/edit#gid=973451281

**Comment by wpsmort** [comment]
Now that the unit tests have been added (PR #1803 ) this issue can be closed.
